from enum import Enum


class RegisteringListenerCode(Enum):
    SELECTED_IMAGES = 0
    IMAGES_READ = 1
    RADIO_BUTTON_CHANGED = 2
    SLICE_SLIDER_CHANGED = 3
    ALPHA_SLIDER_CHANGED = 4
    REGISTERING_WILL_START = 5
    REGISTERING_DID_FINISH = 6


